Milestone-3/webapp/classproj/classproj/Controllers/DiscussionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using classproj.Models;

namespace classproj.Controllers
{
    public class DiscussionsController : Controller
    {
        private DiscussionDB db = new DiscussionDB();

        // GET: Discussions
        public ActionResult Index()
        {
            var discussions = db.Discussions.Include(d => d.User);
            return View(discussions.ToList());
        }

        // GET: Discussions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discussion discussion = db.Discussions.Find(id);
            if (discussion == null)
            {
                return HttpNotFound();
            }
            return View(discussion);
        }

        // GET: Discussions/Create
        public ActionResult Create()
        {
            ViewBag.CreatorID = new SelectList(db.Users, "UserID", "Email");
            return View();
        }

        // POST: Discussions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,CreatorID,Text")] Discussion discussion)
        {
            if (ModelState.IsValid)
            {
                db.Discussions.Add(discussion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CreatorID = new SelectList(db.Users, "UserID", "Email", discussion.CreatorID);
            return View(discussion);
        }

        // GET: Discussions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discussion discussion = db.Discussions.Find(id);
            if (discussion == null)
            {
                return HttpNotFound();
            }
            ViewBag.CreatorID = new SelectList(db.Users, "UserID", "Email", discussion.CreatorID);
            return View(discussion);
        }

        // POST: Discussions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,CreatorID,Timestamp,Text")] Discussion discussion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(discussion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CreatorID = new SelectList(db.Users, "UserID", "Email", discussion.CreatorID);
            return View(discussion);
        }

        // GET: Discussions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discussion discussion = db.Discussions.Find(id);
            if (discussion == null)
            {
                return HttpNotFound();
            }
            return View(discussion);
        }

        // POST: Discussions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Discussion discussion = db.Discussions.Find(id);
            db.Discussions.Remove(discussion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Milestone-3/webapp/classproj/classproj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div>
        <!-- A grey horizontal navbar that becomes vertical on small screens -->
        <nav class="navbar navbar-expand-sm bg-light justify-content-between">

            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Most Viewed", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Discussion Topics", "Index", "Discussions", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Help", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("About Us", "About", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact Us", "Contact", "Home", null, new { @class = "nav-link" })
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </nav>
    </div>
         
    <br />
    <!--The Header of the Pages-->
    <div class="row">
        <div class="col-md-3">
            <div class="center">
                <!--The Logo with Formatting so it doesn't look completely stupid.-->
                <img src="~/Images/logo.PNG" style="width:75%; padding-left:50px;" />
            </div>
        </div>
        <div class="col-md-9">
            <!--The Title of the Site with Formatting-->
            <h1 style="font-size:90px;"><b>Discussion Hub</b></h1>
            <br />
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <!--The Footer Starts here.-->
        <footer>
            <p>&copy; @DateTime.Now.Year - CS 461 2019</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>